// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicePresence } from "./DevicePresence";

export type BatteryInfo = { presence: DevicePresence, 
/**
 * Percent 0..=100.
 */
level: number | null, };
