// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Features a headset exposes over HID.
 */
export type Capability = "sidetone" | "battery_status" | "notification_sound" | "lights" | "inactive_time" | "chat_mix_status" | "voice_prompts" | "rotate_to_mute" | "equalizer_preset" | "equalizer" | "parametric_equalizer" | "microphone_mute_led_brightness" | "microphone_volume" | "volume_limiter" | "bt_when_powered_on" | "bt_call_volume";
