// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Game/chat balance, 0..=100. 0 is all chat, 100 is all game.
 */
export type ChatMix = { value: number, 
/**
 * True when set from the UI/CLI rather than read off the headset wheel.
 */
manual: boolean, };
