// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a device is reachable right now.
 */
export type DevicePresence = "connected" | "absent" | "faulted";
