// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identity of a headset.
 */
export type DeviceId = { vendor_id: number, product_id: number, };
