// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterType } from "./FilterType";

export type EqBand = { freq: number, gain_db: number, q: number, filter_type: FilterType, enabled: boolean, };
