// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBand } from "./EqBand";

export type EqChain = { enabled: boolean, preamp_db: number, bands: Array<EqBand>, };
