// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two managed chains a request refers to.
 */
export type EqChainId = "game" | "chat";
