// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqChain } from "./EqChain";

export type EqPreset = { name: string, builtin: boolean, chain: EqChain, };
