// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqChain } from "./EqChain";
import type { EqChainId } from "./EqChainId";

export type EqState = { 
/**
 * `EqChainId` must stay a unit-only enum: JSON object keys are strings.
 */
chains: { [key in EqChainId]?: EqChain }, 
/**
 * Filter chain failed to load; audio is routed around the EQ.
 */
safe_mode: boolean, };
