// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "version_mismatch" | "bad_request" | "not_found" | "device_absent" | "pipe_wire_unavailable" | "pipe_wire_failed" | "permission_denied" | "conflict" | "internal";
