// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMix } from "./ChatMix";
import type { DeviceId } from "./DeviceId";
import type { EqState } from "./EqState";
import type { SinkInfo } from "./SinkInfo";
import type { StreamInfo } from "./StreamInfo";

export type Event = { "event": "chatmix.changed", "data": ChatMix } | { "event": "eq.state_changed", "data": EqState } | { "event": "eq.safe_mode", "data": { active: boolean, } } | { "event": "graph.changed" } | { "event": "stream.list_changed", "data": { streams: Array<StreamInfo>, } } | { "event": "sink.list_changed", "data": { sinks: Array<SinkInfo>, } } | { "event": "device.attached", "data": { device: DeviceId, } } | { "event": "device.detached", "data": { device: DeviceId, } } | { "event": "device.selection_changed", "data": { device: DeviceId | null, } } | { "event": "daemon.shutting_down" };
