// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterType = "peaking" | "low_shelf" | "high_shelf" | "low_pass" | "high_pass" | "notch";
