// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daemon identity, returned from `session.hello`.
 */
export type Hello = { daemon: string, 
/**
 * Inclusive protocol range this daemon speaks.
 */
proto: [number, number], 
/**
 * Optional feature flags, so clients can degrade rather than guess.
 */
caps: Array<string>, };
