// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned from `session.hello`.
 */
export type Hello = { daemon: string, 
/**
 * Inclusive protocol range this daemon speaks.
 */
proto: [number, number], caps: Array<string>, };
