// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hardware output the user can route a sink to.
 */
export type OutputDevice = { id: number, name: string, description: string, };
