// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One end of a link, in `pw-link`'s `node:port` form.
 */
export type PortRef = { node_name: string, port_name: string, };
