// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortDirection } from "./PortDirection";

/**
 * A port on a node, as addressed by `pw-link`.
 */
export type PortInfo = { id: number, node_name: string, port_name: string, direction: PortDirection, };
