// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

export type PwError = { kind: ErrorKind, msg: string, retryable: boolean, 
/**
 * Set on [`ErrorKind::VersionMismatch`]: the range the daemon speaks.
 */
supported?: [number, number] | null, };
