// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PwError } from "./PwError";
import type { Response } from "./Response";

export type ResponsePayload = { "ok": Response } | { "err": PwError };
