// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMix } from "./ChatMix";
import type { DeviceDescriptor } from "./DeviceDescriptor";
import type { DeviceId } from "./DeviceId";
import type { EqPresetMeta } from "./EqPresetMeta";
import type { EqState } from "./EqState";
import type { Hello } from "./Hello";
import type { LinkInfo } from "./LinkInfo";
import type { OutputDevice } from "./OutputDevice";
import type { PortInfo } from "./PortInfo";
import type { RouteInfo } from "./RouteInfo";
import type { SinkInfo } from "./SinkInfo";
import type { Snapshot } from "./Snapshot";
import type { StreamInfo } from "./StreamInfo";
import type { SystemDeps } from "./SystemDeps";
import type { UdevStatus } from "./UdevStatus";
import type { UserDevice } from "./UserDevice";

export type Response = { "kind": "empty" } | { "kind": "hello", "data": Hello } | { "kind": "snapshot", "data": Snapshot } | { "kind": "streams", "data": Array<StreamInfo> } | { "kind": "sinks", "data": Array<SinkInfo> } | { "kind": "sink_name", "data": string } | { "kind": "route", "data": RouteInfo | null } | { "kind": "output_devices", "data": Array<OutputDevice> } | { "kind": "ports", "data": Array<PortInfo> } | { "kind": "links", "data": Array<LinkInfo> } | { "kind": "devices", "data": Array<DeviceDescriptor> } | { "kind": "selected_device", "data": DeviceId | null } | { "kind": "user_devices", "data": Array<UserDevice> } | { "kind": "chat_mix", "data": ChatMix } | { "kind": "eq_state", "data": EqState } | { "kind": "eq_presets", "data": Array<EqPresetMeta> } | { "kind": "system_deps", "data": SystemDeps } | { "kind": "udev_status", "data": UdevStatus } | { "kind": "icon", "data": string | null };
