// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The card route a sink currently feeds.
 */
export type RouteInfo = { sink: string, device: string, description: string, };
