// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SinkInfo = { id: number, name: string, description: string, 
/**
 * 0..=100.
 */
volume: number, is_muted: boolean, 
/**
 * True for sinks Penguin Wave created; only these are reconciled on startup.
 */
managed: boolean, };
