// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sink as it currently exists in the audio server.
 */
export type SinkInfo = { id: number, name: string, description: string, 
/**
 * 0..=100. Not `f32`: the UI works in whole percent and the audio server
 * is told whole percent, so carrying more precision only invites
 * round-trip drift between client and daemon.
 */
volume: number, is_muted: boolean, 
/**
 * True when Penguin Wave created it, as opposed to a sink that was
 * already there. Only managed sinks are adopted or reconciled on startup.
 */
managed: boolean, };
