// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A virtual sink the daemon creates and owns.
 */
export type SinkConfig = { name: string, display_name: string, };
