// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMix } from "./ChatMix";
import type { DeviceDescriptor } from "./DeviceDescriptor";
import type { DeviceId } from "./DeviceId";
import type { EqState } from "./EqState";
import type { SinkInfo } from "./SinkInfo";
import type { StreamInfo } from "./StreamInfo";
import type { UserDevice } from "./UserDevice";

/**
 * Everything a client needs to render from cold.
 *
 * Returned by `session.snapshot` on connect and on every reconnect.
 */
export type Snapshot = { streams: Array<StreamInfo>, sinks: Array<SinkInfo>, default_sink: string, devices: Array<DeviceDescriptor>, selected_device: DeviceId | null, user_devices: Array<UserDevice>, chatmix: ChatMix, eq: EqState, };
