// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a playback stream.
 *
 * Not a bare index: PulseAudio recycles sink-input indices, so `app_name` and
 * `pid` are revalidated before any mutation.
 */
export type StreamRef = { index: number, app_name: string, pid: number | null, };
