// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a playback stream.
 *
 * Deliberately not a bare index. PulseAudio recycles sink-input indices the
 * moment a stream dies, so a client holding a stale index can silently
 * retarget the wrong application. `index` is the fast path; the rest is
 * revalidated before any mutation, and a mismatch is reported as
 * [`crate::error::ErrorKind::Conflict`] rather than acted on.
 */
export type StreamRef = { index: number, 
/**
 * `application.name` as reported when the client last saw the stream.
 */
app_name: string, 
/**
 * Owning process id, when the audio server reports one.
 */
pid: number | null, };
