// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamInfo = { 
/**
 * Resolved display name.
 */
name: string, sink: string, 
/**
 * 0..=100.
 */
volume: number, is_muted: boolean, 
/**
 * Key for `stream.icon`. Icons are fetched separately, never inlined here.
 */
icon_key: string | null, index: number, app_name: string, pid: number | null, };
