// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A playback stream belonging to some application.
 */
export type StreamInfo = { 
/**
 * Resolved display name: `application.name` -> `application.process.binary`
 * -> `/proc/<pid>/cmdline` -> a `media.role` hybrid label.
 */
name: string, 
/**
 * Sink this stream is currently routed to, by name.
 */
sink: string, 
/**
 * 0..=100.
 */
volume: number, is_muted: boolean, 
/**
 * Opaque key for [`crate::request::Request::StreamIcon`].
 *
 * Resolving an icon walks the filesystem for `.desktop` entries, so it is
 * never done inline in a stream listing. `None` means no icon was found
 * and the client should not ask again.
 */
icon_key: string | null, index: number, 
/**
 * `application.name` as reported when the client last saw the stream.
 */
app_name: string, 
/**
 * Owning process id, when the audio server reports one.
 */
pid: number | null, };
