// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the environment checks behind the Maintenance page.
 */
export type SystemDeps = { pipewire: boolean, pactl: boolean, pw_link: boolean, libhidapi: boolean, };
