// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the udev rule granting HID access is installed.
 */
export type UdevStatus = { installed: boolean, 
/**
 * Argv for the client to run with elevation. The daemon never calls
 * `pkexec` itself; it stays unprivileged.
 */
install_command: Array<string> | null, };
