// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the udev rule granting HID access is installed.
 *
 * When missing, the daemon returns the command for the client to run under
 * its own polkit agent. The daemon never invokes `pkexec` itself: it runs
 * unprivileged, always, and acquiring root even transiently would make the
 * socket's `0600` permission the wrong security boundary.
 */
export type UdevStatus = { installed: boolean, 
/**
 * Populated when `installed` is false: the exact argv the client should
 * run with elevation.
 */
install_command: Array<string> | null, };
