// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device the user added by hand.
 *
 * Ids are 4-digit hex strings; validate with [`is_valid_hex_id`] before use.
 */
export type UserDevice = { name: string, vendor_id: string | null, product_id: string | null, pipewire_sink: string | null, };
