// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device the user added by hand, for hardware with no built-in support.
 *
 * `vendor_id` / `product_id` stay `String` on the wire because they are
 * entered as 4-digit hex and written into a root-owned udev rules file.
 * Validate with [`is_valid_hex_id`] before interpolating them anywhere.
 */
export type UserDevice = { name: string, vendor_id: string | null, product_id: string | null, pipewire_sink: string | null, };
