//! Generates the PipeWire filter-chain config for both EQ chains.
//!
//! The graph is static: MAX_BANDS `bq_raw` nodes + 1 preamp node per chain,
//! all initialized to identity. Real coefficients are pushed live via Props
//! after startup (live.rs), so the conf never needs regeneration for band
//! edits — only the topology lives here.

use crate::eq::nodes::{output_node_name, sink_node_name, source_sink_for};
use penguinwave_proto::{EqChainId, MAX_BANDS};

pub const PREAMP_NODE: &str = "preamp";

pub fn band_node_name(index: usize) -> String {
    format!("eq_b{}", index)
}

fn identity_node(name: &str) -> String {
    format!(
        "                    {{ type = builtin name = {name} label = bq_raw\n\
         \x20                     config = {{ coefficients = [\n\
         \x20                         {{ rate = 48000 b0 = 1.0 b1 = 0.0 b2 = 0.0 a1 = 0.0 a2 = 0.0 }}\n\
         \x20                     ] }}\n\
         \x20                   }}"
    )
}

fn chain_module(chain: EqChainId) -> String {
    let mut nodes = vec![identity_node(PREAMP_NODE)];
    let mut links = Vec::new();

    let mut prev = PREAMP_NODE.to_string();
    for i in 0..MAX_BANDS {
        let name = band_node_name(i);
        nodes.push(identity_node(&name));
        links.push(format!(
            "                    {{ output = \"{prev}:Out\" input = \"{name}:In\" }}"
        ));
        prev = name;
    }

    format!(
        r#"    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = "{description}"
            media.name       = "{description}"
            filter.graph = {{
                nodes = [
{nodes}
                ]
                links = [
{links}
                ]
            }}
            capture.props = {{
                node.name   = "{sink_name}"
                # capture the monitor of the existing virtual sink instead of
                # exposing a second Audio/Sink (would pollute the sink list)
                target.object = "{source_sink}"
                stream.capture.sink = true
                node.passive = true
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
            playback.props = {{
                node.name   = "{output_name}"
                node.passive = true
                audio.channels = 2
                audio.position = [ FL FR ]
            }}
        }}
    }}"#,
        description = chain.description(),
        sink_name = sink_node_name(chain),
        source_sink = source_sink_for(chain),
        output_name = output_node_name(chain),
        nodes = nodes.join("\n"),
        links = links.join("\n"),
    )
}

/// Full standalone PipeWire config running both EQ chains in one process.
pub fn generate_conf() -> String {
    let modules: Vec<String> = EqChainId::ALL.iter().map(|&c| chain_module(c)).collect();

    format!(
        r#"# Generated by PenguinWave — do not edit (regenerated on startup).
context.properties = {{
    log.level = 2
}}

context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}}

context.modules = [
    {{ name = libpipewire-module-rt
        args = {{ nice.level = -11 }}
        flags = [ ifexists nofail ]
    }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}

{modules}
]
"#,
        modules = modules.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conf_contains_both_chains() {
        let conf = generate_conf();
        assert!(conf.contains("penguinwave_eq_game"));
        assert!(conf.contains("penguinwave_eq_chat"));
        assert!(conf.contains("penguinwave_eq_game_out"));
        assert!(conf.contains("penguinwave_eq_chat_out"));
    }

    #[test]
    fn eq_captures_existing_sinks_instead_of_creating_new_ones() {
        let conf = generate_conf();
        // must NOT register additional Audio/Sink devices
        assert!(!conf.contains("media.class = Audio/Sink"));
        // must capture the existing virtual sinks' monitors
        assert!(conf.contains(r#"target.object = "game_sink""#));
        assert!(conf.contains(r#"target.object = "chat_sink""#));
        assert_eq!(conf.matches("stream.capture.sink = true").count(), 2);
    }

    #[test]
    fn conf_has_pool_of_bq_raw_nodes_per_chain() {
        let conf = generate_conf();
        // MAX_BANDS band nodes + 1 preamp, per chain
        assert_eq!(
            conf.matches("label = bq_raw").count(),
            (MAX_BANDS + 1) * EqChainId::ALL.len()
        );
        assert_eq!(conf.matches("name = preamp").count(), EqChainId::ALL.len());
        // last band node exists, one past the end doesn't
        assert!(conf.contains(&format!("name = {} ", band_node_name(MAX_BANDS - 1))));
        assert!(!conf.contains(&format!("name = {} ", band_node_name(MAX_BANDS))));
    }

    #[test]
    fn chain_is_linked_in_series() {
        let conf = generate_conf();
        assert!(conf.contains(r#"{ output = "preamp:Out" input = "eq_b0:In" }"#));
        assert!(conf.contains(&format!(
            r#"{{ output = "{}:Out" input = "{}:In" }}"#,
            band_node_name(MAX_BANDS - 2),
            band_node_name(MAX_BANDS - 1)
        )));
    }

    #[test]
    fn all_nodes_start_as_identity() {
        let conf = generate_conf();
        assert_eq!(
            conf.matches("b0 = 1.0 b1 = 0.0 b2 = 0.0 a1 = 0.0 a2 = 0.0")
                .count(),
            (MAX_BANDS + 1) * EqChainId::ALL.len()
        );
    }
}
