//! Dependency and udev-rule checks.
//!
//! Read-only: the daemon stays unprivileged and never installs anything
//! itself. Installation is returned as a command for the client to run under
//! its own polkit agent.

use penguinwave_hid::{DeviceRegistry, HidBackend};
use penguinwave_proto::{is_valid_hex_id, SystemDeps, UdevStatus, UserDevice};
use std::path::{Path, PathBuf};

pub const RULES_PATH: &str = "/etc/udev/rules.d/99-penguinwave.rules";

/// Whether an executable of this name exists on `PATH`.
fn on_path(program: &str) -> bool {
    std::env::var_os("PATH")
        .map(|paths| {
            std::env::split_paths(&paths).any(|dir| {
                let candidate = dir.join(program);
                candidate.is_file()
            })
        })
        .unwrap_or(false)
}

pub fn check_deps(hid: &dyn HidBackend) -> SystemDeps {
    SystemDeps {
        pipewire: on_path("pipewire"),
        pactl: on_path("pactl"),
        pw_link: on_path("pw-link"),
        libhidapi: hid.available(),
    }
}

/// The rules file this build expects, for every supported and user device.
pub fn expected_rules(devices: &DeviceRegistry, user_devices: &[UserDevice]) -> String {
    let mut lines = vec![
        format!("# {RULES_PATH}"),
        "# Penguin Wave: hidraw access for headset devices".to_string(),
        "# Generated by Penguin Wave; edits are overwritten".to_string(),
        String::new(),
    ];

    for d in devices.descriptors() {
        lines.push(format!("# {}", d.name));
        lines.push(rule(d.id.vendor_id_hex(), Some(d.id.product_id_hex())));
        lines.push(String::new());
    }

    for ud in user_devices {
        // Defence in depth: only 4-hex-digit ids are safe to interpolate into
        // an udev match, and a hand-edited devices.toml has not been through
        // the add path's validation.
        let (Some(vid), Some(pid)) = (ud.vendor_id.as_deref(), ud.product_id.as_deref()) else {
            continue;
        };
        if !is_valid_hex_id(vid) || !is_valid_hex_id(pid) {
            continue;
        }
        lines.push(format!("# {} (user defined)", ud.name));
        lines.push(rule(vid.to_string(), Some(pid.to_string())));
        lines.push(String::new());
    }

    lines.join("\n")
}

fn rule(vendor: String, product: Option<String>) -> String {
    match product {
        Some(product) => format!(
            "KERNEL==\"hidraw*\", ATTRS{{idVendor}}==\"{vendor}\", ATTRS{{idProduct}}==\"{product}\", MODE=\"0666\""
        ),
        None => {
            format!("KERNEL==\"hidraw*\", ATTRS{{idVendor}}==\"{vendor}\", MODE=\"0666\"")
        }
    }
}

pub fn check_udev(devices: &DeviceRegistry, user_devices: &[UserDevice]) -> UdevStatus {
    check_udev_at(Path::new(RULES_PATH), devices, user_devices)
}

pub fn check_udev_at(
    path: &Path,
    devices: &DeviceRegistry,
    user_devices: &[UserDevice],
) -> UdevStatus {
    let expected = expected_rules(devices, user_devices);
    let current = std::fs::read_to_string(path).ok();
    let installed = current.as_deref() == Some(expected.as_str());

    UdevStatus {
        installed,
        install_command: if installed {
            None
        } else {
            Some(install_command(path, &expected))
        },
    }
}

/// Argv for the client to run with elevation.
///
/// The content is passed through a single-quoted shell word, so every embedded
/// quote is closed and reopened rather than escaped; the rules text is
/// generated, but it carries user-supplied device names.
pub fn install_command(path: &Path, content: &str) -> Vec<String> {
    let quoted = shell_quote(content);
    let target = shell_quote(&path.display().to_string());
    vec![
        "pkexec".into(),
        "sh".into(),
        "-c".into(),
        format!(
            "printf '%s\\n' {quoted} > {target} && udevadm control --reload-rules && udevadm trigger"
        ),
    ]
}

fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

pub fn rules_path() -> PathBuf {
    PathBuf::from(RULES_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quoting_survives_an_embedded_quote() {
        assert_eq!(shell_quote("a'b"), r"'a'\''b'");
    }

    #[test]
    fn a_device_name_cannot_break_out_of_the_command() {
        let cmd = install_command(Path::new("/tmp/x"), "'; rm -rf / #");
        let script = cmd.last().unwrap();
        assert!(script.contains(r"'\''; rm -rf / #'"));
        assert!(!script.contains("' ; rm"));
    }
}
